services:
  medisupply-db:
    image: postgres:17
    container_name: medisupply-postgres
    environment:
      POSTGRES_DB: medisupply_local_db
      POSTGRES_USER: medisupply_local_user
      POSTGRES_PASSWORD: medisupply_local_password
    volumes:
      - medisupply_data:/var/lib/postgresql/data
      - ./db/init/medisupply_init.sql:/docker-entrypoint-initdb.d/medisupply_init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - medisupply-net

  keycloak:
    image: keycloak/keycloak:26.3
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: medisupply_local_user
      KC_DB_PASSWORD: medisupply_local_password
      KC_DB_URL: jdbc:postgresql://medisupply-db:5432/medisupply_local_db
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import:ro
    depends_on: [medisupply-db]
    networks:
      - medisupply-net

  autenticador:
    image: medisupply-autenticador
    container_name: medisupply-autenticador
    build:
      context: ../proyecto-integrador-medisupply-autenticador-backend
    environment:
      - HOST=0.0.0.0
      - DEBUG=true
      - DATABASE_URL=postgresql://medisupply_local_user:medisupply_local_password@medisupply-db:5432/medisupply_local_db
      - KC_BASE_URL=http://keycloak:8080
      - KC_ADMIN_USER=admin
      - KC_ADMIN_PASSWORD=admin
      - GCP_PROJECT_ID=clean-result-473723-t3
      - BUCKET_NAME=medisupply-images-bucket
      - BUCKET_FOLDER=users
      - BUCKET_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - SIGNING_SERVICE_ACCOUNT_EMAIL=medisupply-signing@clean-result-473723-t3.iam.gserviceaccount.com
    volumes:
      - ./credentials/gcp-credentials.json:/tmp/gcp-credentials.json:ro
    ports:
      - "8081:8080"
    depends_on: [medisupply-db]
    networks:
      - medisupply-net

  autorizador:
    image: medisupply-autorizador
    container_name: medisupply-autorizador
    build:
      context: ../proyecto-integrador-medisupply-autorizador-backend
    environment:
      - HOST=0.0.0.0
      - DEBUG=true
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=medisupply-realm
      - KEYCLOAK_CLIENT_ID=medisupply-app
      - AUTHENTICATOR_SERVICE_URL=http://autenticador:8080
      - INVENTORIES_SERVICE_URL=http://inventarios:8080
      - PROVIDERS_SERVICE_URL=http://proveedores:8080
      - ORDERS_SERVICE_URL=http://pedidos:8080
      - SALES_PLAN_SERVICE_URL=http://plan-ventas:8080
      - LOGISTICS_SERVICE_URL=http://logistica:8080
    ports:
      - "8082:8080"
    depends_on: [keycloak]
    networks:
      - medisupply-net

  proveedores:
    image: medisupply-proveedores
    container_name: medisupply-proveedores
    build:
      context: ../proyecto-integrador-medisupply-proveedores-backend
    environment:
      - HOST=0.0.0.0
      - DEBUG=true
      - DATABASE_URL=postgresql://medisupply_local_user:medisupply_local_password@medisupply-db:5432/medisupply_local_db
      - GCP_PROJECT_ID=clean-result-473723-t3
      - BUCKET_NAME=medisupply-images-bucket
      - BUCKET_FOLDER=providers
      - BUCKET_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - SIGNING_SERVICE_ACCOUNT_EMAIL=medisupply-signing@clean-result-473723-t3.iam.gserviceaccount.com
    volumes:
      - ./credentials/gcp-credentials.json:/tmp/gcp-credentials.json:ro
    ports:
      - "8083:8080"
    depends_on: [medisupply-db]
    networks:
      - medisupply-net

  inventarios:
    image: medisupply-inventarios
    container_name: medisupply-inventarios
    build:
      context: ../proyecto-integrador-medisupply-inventarios-backend
    environment:
      - HOST=0.0.0.0
      - DEBUG=true
      - DATABASE_URL=postgresql://medisupply_local_user:medisupply_local_password@medisupply-db:5432/medisupply_local_db
      - GCP_PROJECT_ID=clean-result-473723-t3
      - BUCKET_NAME=medisupply-images-bucket
      - BUCKET_FOLDER=products
      - BUCKET_FOLDER_PROCESSED_PRODUCTS=processed-products
      - BUCKET_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - SIGNING_SERVICE_ACCOUNT_EMAIL=medisupply-signing@clean-result-473723-t3.iam.gserviceaccount.com
      - PROVIDERS_SERVICE_URL=http://proveedores:8080
      - AUTHENTICATOR_SERVICE_URL=http://autenticador:8080
      - PUBSUB_EMULATOR_HOST=pubsub:8120
      - PUBSUB_TOPIC_PRODUCTS_IMPORT=inventory.processing.products
    volumes:
      - ./credentials/gcp-credentials.json:/tmp/gcp-credentials.json:ro
    ports:
      - "8084:8080"
    depends_on: [medisupply-db]
    networks:
      - medisupply-net

  pedidos:
    image: medisupply-pedidos
    container_name: medisupply-pedidos
    build:
      context: ../proyecto-integrador-medisupply-pedidos-backend
    environment:
      - HOST=0.0.0.0
      - DEBUG=true
      - DATABASE_URL=postgresql://medisupply_local_user:medisupply_local_password@medisupply-db:5432/medisupply_local_db
      - INVENTORY_SERVICE_URL=http://inventarios:8080
      - AUTH_SERVICE_URL=http://autenticador:8080
    ports:
      - "8085:8080"
    depends_on: [medisupply-db]
    networks:
      - medisupply-net

  inventarios-procesador:
    image: medisupply-inventarios-procesador
    container_name: medisupply-inventarios-procesador
    build:
      context: ../proyecto-integrador-medisupply-inventarios-procesador-backend
    environment:
      - HOST=0.0.0.0
      - DEBUG=true
      - DATABASE_URL=postgresql://medisupply_local_user:medisupply_local_password@medisupply-db:5432/medisupply_local_db
      - GCP_PROJECT_ID=clean-result-473723-t3
      - BUCKET_NAME=medisupply-images-bucket
      - BUCKET_FOLDER_PROCESSED_PRODUCTS=processed-products
      - BUCKET_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - SIGNING_SERVICE_ACCOUNT_EMAIL=medisupply-signing@clean-result-473723-t3.iam.gserviceaccount.com
    volumes:
      - ./credentials/gcp-credentials.json:/tmp/gcp-credentials.json:ro
    ports:
      - "8086:8080"
    depends_on: [medisupply-db]
    networks:
      - medisupply-net

  plan-ventas:
    image: medisupply-plan-ventas
    container_name: medisupply-plan-ventas
    build:
      context: ../proyecto-integrador-medisupply-plan-ventas-backend
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DEBUG=true
      - DATABASE_URL=postgresql://medisupply_local_user:medisupply_local_password@medisupply-db:5432/medisupply_local_db
      - GCP_PROJECT_ID=clean-result-473723-t3
      - AUTH_SERVICE_URL=http://autenticador:8080
      - BUCKET_NAME=medisupply-images-bucket
      - BUCKET_FOLDER=sales-plan
      - BUCKET_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - SIGNING_SERVICE_ACCOUNT_EMAIL=medisupply-signing@clean-result-473723-t3.iam.gserviceaccount.com
      - PUBSUB_TOPIC_VIDEO_PROCESSING=salesplan.processing.videos
      - PUBSUB_EMULATOR_HOST=pubsub:8120
    volumes:
      - ./credentials/gcp-credentials.json:/tmp/gcp-credentials.json:ro
    ports:
      - "8087:8080"
    depends_on: [medisupply-db, autenticador]
    networks:
      - medisupply-net

  logistica:
    image: medisupply-logistica
    container_name: medisupply-logistica
    build:
      context: ../proyecto-integrador-medisupply-logistica-backend
    environment:
      - HOST=0.0.0.0
      - DEBUG=true
      - DATABASE_URL=postgresql://medisupply_local_user:medisupply_local_password@medisupply-db:5432/medisupply_local_db
      - ORDERS_SERVICE_URL=http://pedidos:8080
      - AUTH_SERVICE_URL=http://autenticador:8080
    ports:
      - "8088:8080"
    depends_on: [medisupply-db, pedidos, autenticador]
    networks:
      - medisupply-net

  archivos-procesador:
    image: medisupply-archivos-procesador
    container_name: medisupply-archivos-procesador
    build:
      context: ../proyecto-integrador-medisupply-procesador-archivos-backend
    environment:
      - HOST=0.0.0.0
      - DEBUG=true
      - DATABASE_URL=postgresql://medisupply_local_user:medisupply_local_password@medisupply-db:5432/medisupply_local_db
      - GCP_PROJECT_ID=clean-result-473723-t3
      - BUCKET_NAME=medisupply-images-bucket
      - BUCKET_FOLDER=sales-plan
      - BUCKET_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
      - SIGNING_SERVICE_ACCOUNT_EMAIL=medisupply-signing@clean-result-473723-t3.iam.gserviceaccount.com
    volumes:
      - ./credentials/gcp-credentials.json:/tmp/gcp-credentials.json:ro
    ports:
      - "8089:8080"
    depends_on: [medisupply-db]
    networks:
      - medisupply-net

  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    volumes:
      - ./pubsub:/pubsub
    command: sh -c "dos2unix /pubsub/init-local.sh 2>/dev/null || sed -i 's/\r$$//' /pubsub/init-local.sh; sh /pubsub/init-local.sh"
    ports:
      - "8120:8120"
    networks:
      - medisupply-net

volumes:
  medisupply_data:

networks:
  medisupply-net:
    driver: bridge